/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_ProviderService 
 * Description : Service-layer placeholder behind VTXP_ProviderAllocationApi.
 *               Later resolves provider license and number assignments.
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_ProviderService {
    public VTXP_ProviderService() {

    }
}