/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_UsageIngestionApi  
 * Description : Apex REST endpoint for receiving usage/call event payloads from subscriber orgs.
 *               URL: /services/apexrest/vtxp/v1/usage/*.
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_UsageIngestionApi {
    public VTXP_UsageIngestionApi() {

    }
}