/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_ResponseDTO 
 * Description : Standard response wrapper for Partner APIs and controllers.
 *               Holds success, message, dataJson, and errorCode.
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */

public with sharing class VTXP_ResponseDTO {
    public VTXP_ResponseDTO() {

    }

    
}