/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_EntitlementApi  
 * Description : Apex REST endpoint for subscriber entitlement/license validation.
 *               URL: /services/apexrest/vtxp/v1/entitlements/*.
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_EntitlementApi {
    public VTXP_EntitlementApi() {

    }
}