/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_ProviderAllocationApi  
 * Description : Apex REST endpoint for returning provider/license/number allocation information.
 *               URL: /services/apexrest/vtxp/v1/providers/*.
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_ProviderAllocationApi {
    public VTXP_ProviderAllocationApi() {

    }
}