/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_SecurityUtil 
 * Description : Dynamic CRUD/FLS helper using Schema methods. 
 *              Provides objectExists, fieldExists, and object/field access checks. 
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_SecurityUtil {
    public VTXP_SecurityUtil() {

    }
}