/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_BillingService
 * Description : Aggregate usage and stage invoices
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_BillingService {
    public VTXP_BillingService() {

    }
}