/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_LmaSyncService
 * Description : Bridge Salesforce LMA license data into Partner objects.
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_LmaSyncService {
    public VTXP_LmaSyncService() {

    }
}