/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_ControlApiLogService 
 * Description : Create API logs and correlate request IDs
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_ControlApiLogService {
    public VTXP_ControlApiLogService() {

    }
}