/**
* Name          :VTXP_Logger 
* Description   :Central logging helper. Sprint 1 implementation should use System.
*                debug only and must not insert log records. 
*
* Author        :Anamika Sharma
* Created Date  :15/07/26
*
* Modification History
* -------------------------------------------------------------------------------------------------
* Version    Date          Author              Description
* -------------------------------------------------------------------------------------------------
* 1.0        15/07/26      Anamika Sharma      Initial Version
* -------------------------------------------------------------------------------------------------
*/
public with sharing class VTXP_Logger {
    public VTXP_Logger() {

    }
}