/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_HeartbeatApi 
 * Description : Apex REST endpoint for subscriber org package health, heartbeat, and status reporting.
 *               URL: /services/apexrest/vtxp/v1/heartbeat/*. 
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_HeartbeatApi {
    public VTXP_HeartbeatApi() {

    }
}