/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_SubscriberOrgService  
 * Description : Register/update/find subscriber org
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_SubscriberOrgService {
    public VTXP_SubscriberOrgService() {

    }
}