/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_ErrorDTO 
 * Description : Standard error payload for structured error details, 
 *              validation failures, and future API error responses
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */

public with sharing class VTXP_ErrorDTO {
    public VTXP_ErrorDTO() {

    }
}