/**
 * -----------------------------------------------------------------------------
 * Name        : VTXP_EntitlementResponseBuilder  
 * Description : Build response JSON for subscriber sync.
 *
 * Author      : Anamika Sharma
 * Created On  : 15-Jul-2026
 *
 * Modification Log
 * -----------------------------------------------------------------------------
 * Ver    Date         Author            Description
 * -----  -----------  ----------------  -----------------------------
 * 1.0    15-Jul-2026  Anamika Sharma    Initial Version
 * -----------------------------------------------------------------------------
 */
public with sharing class VTXP_EntitlementResponseBuilder {
    public VTXP_EntitlementResponseBuilder() {

    }
}